### ISSUE TITLE
Doesn't handle localized webstore URLs

### ISSUE THREAD

**Issue by swissspidy** [vladignatyev/crx-extractor#2]
The query part from the webstore URLs isn't stripped off correctly.

To give you an example, pasting the following URL works:

```
https://chrome.google.com/webstore/detail/right-inbox-for-gmail/mflnemhkomgploogccdmcloekbloobgb
```

But this one does not:

```
https://chrome.google.com/webstore/detail/right-inbox-for-gmail/mflnemhkomgploogccdmcloekbloobgb?hl=de
```

Also, why do I need to download and re-upload the crx file? It should get

**Comment by vladignatyev** [comment]
@swissspidy thanks for posting this issue!

Answering your question about why you're required to reupload .crx file, I would tell that there is no possibility in JS (I mean browser environment) to do so without re-uploading. All the logic behind the site implemented completely browser-side. Probably in further releases I will add backend and make server-side processing, because it has lots of advantages as well.
